# Generated by Django 5.2.8 on 2025-12-01 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('group_type', models.CharField(choices=[('location', 'По местоположению'), ('function', 'По функциям'), ('priority', 'По приоритету'), ('custom', 'Пользовательская')], default='custom', max_length=20, verbose_name='Тип группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('alert_threshold', models.FloatField(default=40.0, verbose_name='Порог оповещения (%)')),
                ('maintenance_schedule', models.CharField(blank=True, max_length=100, null=True, verbose_name='График обслуживания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа роботов',
                'verbose_name_plural': 'Группы роботов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=50, unique=True, verbose_name='ID робота')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('robot_type', models.CharField(choices=[('warehouse', 'Складской'), ('production', 'Производственный'), ('delivery', 'Доставки'), ('inspection', 'Инспекционный'), ('cleaning', 'Уборки'), ('security', 'Безопасности')], default='warehouse', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('idle', 'Простой'), ('warning', 'Предупреждение'), ('critical', 'Критический'), ('maintenance', 'На обслуживании'), ('offline', 'Офлайн')], default='active', max_length=20, verbose_name='Статус')),
                ('battery_level', models.FloatField(default=100.0, verbose_name='Заряд батареи (%)')),
                ('temperature', models.FloatField(default=25.0, verbose_name='Температура (°C)')),
                ('cpu_load', models.FloatField(default=0.0, verbose_name='Загрузка CPU (%)')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='Использование памяти (%)')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('current_task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текущая задача')),
                ('assigned_tasks', models.IntegerField(default=0, verbose_name='Всего задач')),
                ('operational_hours', models.FloatField(default=0.0, verbose_name='Часов в работе')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обслуживание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='dashboard.robotgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Робот',
                'verbose_name_plural': 'Роботы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отчета')),
                ('report_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('custom', 'Пользовательский'), ('alert_summary', 'Сводка по оповещениям'), ('performance', 'Производительность'), ('maintenance', 'Обслуживание')], default='daily', max_length=20, verbose_name='Тип отчета')),
                ('time_period', models.CharField(choices=[('today', 'Сегодня'), ('yesterday', 'Вчера'), ('last_7_days', 'Последние 7 дней'), ('last_30_days', 'Последние 30 дней'), ('this_month', 'Этот месяц'), ('last_month', 'Прошлый месяц'), ('custom', 'Выбрать период')], default='today', max_length=20, verbose_name='Период')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('report_data', models.JSONField(verbose_name='Данные отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
                ('file_format', models.CharField(default='pdf', max_length=10, verbose_name='Формат файла')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('robot_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dashboard.robotgroup', verbose_name='Группа роботов')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время показания')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('battery_level', models.FloatField(verbose_name='Уровень заряда (%)')),
                ('cpu_load', models.FloatField(verbose_name='Загрузка CPU (%)')),
                ('memory_usage', models.FloatField(verbose_name='Использование памяти (%)')),
                ('location_x', models.FloatField(default=0.0, verbose_name='Координата X')),
                ('location_y', models.FloatField(default=0.0, verbose_name='Координата Y')),
                ('active_tasks', models.IntegerField(default=0, verbose_name='Активные задачи')),
                ('signal_strength', models.FloatField(blank=True, null=True, verbose_name='Сила сигнала')),
                ('error_count', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Показание датчиков',
                'verbose_name_plural': 'Показания датчиков',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Критическое'), ('warning', 'Предупреждение'), ('maintenance', 'Обслуживание'), ('info', 'Информационное')], default='warning', max_length=20, verbose_name='Тип оповещения')),
                ('severity', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критический')], default=2, verbose_name='Уровень серьезности')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('trigger_value', models.FloatField(blank=True, null=True, verbose_name='Значение триггера')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Пороговое значение')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', 'alert_type'], name='dashboard_a_resolve_6c68d1_idx'), models.Index(fields=['robot', '-created_at'], name='dashboard_a_robot_i_c42718_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['status'], name='dashboard_r_status_a65f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['robot_type'], name='dashboard_r_robot_t_540dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['battery_level'], name='dashboard_r_battery_39a643_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', '-generated_at'], name='dashboard_r_report__4833be_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['robot_group', '-generated_at'], name='dashboard_r_robot_g_24b9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='robotreading',
            index=models.Index(fields=['robot', '-timestamp'], name='dashboard_r_robot_i_2feffa_idx'),
        ),
        migrations.AddIndex(
            model_name='robotreading',
            index=models.Index(fields=['-timestamp'], name='dashboard_r_timesta_4aa45a_idx'),
        ),
    ]
